// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Go Swagger Example",
    "version": "0.1.0"
  },
  "paths": {
    "/tweets": {
      "get": {
        "tags": [
          "tweets"
        ],
        "summary": "List the tweets",
        "operationId": "tweetsList",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Tweet"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Tweet": {
      "type": "object",
      "required": [
        "contents"
      ],
      "properties": {
        "contents": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "x-go-custom-tag": "gorm:\"primary_key\"",
          "readOnly": true
        },
        "numberOfCharacters": {
          "type": "integer",
          "minimum": 1
        },
        "userId": {
          "type": "integer",
          "readOnly": true
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Go Swagger Example",
    "version": "0.1.0"
  },
  "paths": {
    "/tweets": {
      "get": {
        "tags": [
          "tweets"
        ],
        "summary": "List the tweets",
        "operationId": "tweetsList",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Tweet"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Tweet": {
      "type": "object",
      "required": [
        "contents"
      ],
      "properties": {
        "contents": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "x-go-custom-tag": "gorm:\"primary_key\"",
          "readOnly": true
        },
        "numberOfCharacters": {
          "type": "integer",
          "minimum": 1
        },
        "userId": {
          "type": "integer",
          "readOnly": true
        }
      }
    }
  }
}`))
}
