// Code generated by go-swagger; DO NOT EDIT.

package tweets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewTweetsListParams creates a new TweetsListParams object
// no default values defined in spec.
func NewTweetsListParams() TweetsListParams {

	return TweetsListParams{}
}

// TweetsListParams contains all the bound params for the tweets list operation
// typically these are obtained from a http.Request
//
// swagger:parameters tweetsList
type TweetsListParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTweetsListParams() beforehand.
func (o *TweetsListParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
